import { type User } from "../services/auth.service";

export const SUELDOS_PERMISSIONS = [
  "sueldos.ver",
  "sueldos.crear",
  "sueldos.editar",
  "sueldos.eliminar",
] as const;

export const MODULE_PERMISSIONS = [
  "contratos.ver",
  "contratos.crear",
  "contratos.editar",
  "contratos.eliminar",
  "caja_chica.ver",
  "caja_chica.crear",
  "caja_chica.eliminar",
  "caja_chica.cerrar",
  "caja_chica.reabrir",
  "liquidaciones.ver",
  "liquidaciones.crear",
  "liquidaciones.editar",
  "liquidaciones.confirmar",
  "liquidaciones.pagar_propietario",
  "liquidaciones.adelantar_propietario",
  "liquidaciones.ajustar",
  "liquidaciones.anular_pago_propietario",
  "liquidaciones.eliminar",
  "pagos.ver",
  "pagos.crear",
  "pagos.eliminar",
  "propiedades.ver",
  "propiedades.crear",
  "propiedades.editar",
  "propiedades.eliminar",
  "personas.ver",
  "personas.crear",
  "personas.editar",
  "personas.eliminar",
  "usuarios.ver",
  "usuarios.crear",
  "usuarios.editar",
  "usuarios.eliminar",
  "usuarios.permisos",
  "usuarios.asignar_rol",
  "configuracion.perfil.ver",
  "configuracion.perfil.editar",
  "configuracion.backups.ver",
  "configuracion.backups.crear",
  "configuracion.backups.eliminar",
  "configuracion.backups.descargar",
  "configuracion.auditoria.ver",
  "reportes.dashboard.ver",
  "reportes.contratos.ver",
  "reportes.morosidad.ver",
  "reportes.financieros.ver",
  "contratos.archivos.ver",
  "contratos.restaurar",
  ...SUELDOS_PERMISSIONS,
] as const;

export type PermissionKey = typeof MODULE_PERMISSIONS[number];

export const PERMISSION_LABELS: Record<PermissionKey, string> = {
  "contratos.ver": "Ver contratos",
  "contratos.crear": "Crear contratos",
  "contratos.editar": "Editar contratos",
  "contratos.eliminar": "Eliminar contratos",
  "caja_chica.ver": "Ver gestión financiera",
  "caja_chica.crear": "Registrar movimientos financieros",
  "caja_chica.eliminar": "Anular movimientos manuales de caja",
  "caja_chica.cerrar": "Cerrar períodos de caja",
  "caja_chica.reabrir": "Reabrir períodos de caja",
  "liquidaciones.ver": "Ver liquidaciones",
  "liquidaciones.crear": "Crear liquidaciones",
  "liquidaciones.editar": "Editar liquidaciones",
  "liquidaciones.confirmar": "Confirmar liquidaciones",
  "liquidaciones.pagar_propietario": "Pagar a propietarios",
  "liquidaciones.adelantar_propietario": "Adelantar fondos a propietarios",
  "liquidaciones.ajustar": "Emitir ajustes de liquidación",
  "liquidaciones.anular_pago_propietario": "Anular pagos a propietarios",
  "liquidaciones.eliminar": "Eliminar liquidaciones",
  "pagos.ver": "Ver pagos",
  "pagos.crear": "Crear pagos",
  "pagos.eliminar": "Anular pagos",
  "propiedades.ver": "Ver propiedades",
  "propiedades.crear": "Crear propiedades",
  "propiedades.editar": "Editar propiedades",
  "propiedades.eliminar": "Eliminar propiedades",
  "personas.ver": "Ver personas",
  "personas.crear": "Crear personas",
  "personas.editar": "Editar personas",
  "personas.eliminar": "Eliminar personas",
  "usuarios.ver": "Ver usuarios",
  "usuarios.crear": "Crear usuarios",
  "usuarios.editar": "Editar usuarios",
  "usuarios.eliminar": "Eliminar usuarios",
  "usuarios.permisos": "Administrar permisos",
  "usuarios.asignar_rol": "Asignar roles",
  "configuracion.perfil.ver": "Ver perfil",
  "configuracion.perfil.editar": "Editar perfil",
  "configuracion.backups.ver": "Ver backups",
  "configuracion.backups.crear": "Crear backups",
  "configuracion.backups.eliminar": "Eliminar backups",
  "configuracion.backups.descargar": "Descargar backups",
  "configuracion.auditoria.ver": "Ver auditoría",
  "reportes.dashboard.ver": "Ver dashboard",
  "reportes.contratos.ver": "Ver métricas de contratos",
  "reportes.morosidad.ver": "Ver morosidad",
  "reportes.financieros.ver": "Ver reportes financieros",
  "contratos.archivos.ver": "Ver archivos de contratos",
  "contratos.restaurar": "Restaurar contratos",
  "sueldos.ver": "Ver sueldos",
  "sueldos.crear": "Crear sueldos",
  "sueldos.editar": "Editar sueldos",
  "sueldos.eliminar": "Eliminar sueldos",
};

export const PERMISSION_GROUPS: Array<{ title: string; permissions: PermissionKey[] }> = [
  { title: "Contratos", permissions: ["contratos.ver", "contratos.crear", "contratos.editar", "contratos.eliminar", "contratos.archivos.ver", "contratos.restaurar"] },
  { title: "Gestión financiera", permissions: ["caja_chica.ver", "caja_chica.crear", "caja_chica.eliminar", "caja_chica.cerrar", "caja_chica.reabrir"] },
  { title: "Liquidaciones", permissions: ["liquidaciones.ver", "liquidaciones.crear", "liquidaciones.editar", "liquidaciones.confirmar", "liquidaciones.pagar_propietario", "liquidaciones.adelantar_propietario", "liquidaciones.ajustar", "liquidaciones.anular_pago_propietario", "liquidaciones.eliminar"] },
  { title: "Pagos", permissions: ["pagos.ver", "pagos.crear", "pagos.eliminar"] },
  { title: "Propiedades", permissions: ["propiedades.ver", "propiedades.crear", "propiedades.editar", "propiedades.eliminar"] },
  { title: "Personas", permissions: ["personas.ver", "personas.crear", "personas.editar", "personas.eliminar"] },
  { title: "Usuarios", permissions: ["usuarios.ver", "usuarios.crear", "usuarios.editar", "usuarios.eliminar", "usuarios.permisos", "usuarios.asignar_rol"] },
  { title: "Configuración", permissions: ["configuracion.perfil.ver", "configuracion.perfil.editar", "configuracion.backups.ver", "configuracion.backups.crear", "configuracion.backups.descargar", "configuracion.backups.eliminar", "configuracion.auditoria.ver"] },
  { title: "Reportes", permissions: ["reportes.dashboard.ver", "reportes.contratos.ver", "reportes.morosidad.ver", "reportes.financieros.ver"] },
  { title: "Sueldos", permissions: [...SUELDOS_PERMISSIONS] },
];

export function isAdminRole(role?: string): boolean {
  return role === "ADMIN";
}

export function hasPermission(user: User | null | undefined, permission: PermissionKey): boolean {
  if (!user) return false;
  if (user.tipo === "ADMIN") return true;
  return !!user.permissions?.includes(permission);
}
